name: Documentation
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Generate documentation with LDoc
        uses: lunarmodules/ldoc@v1.5.0
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: doc
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: doc
